name: Release
on:
  push:
    branches:
      - master
      - 'ci/**'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - name: Semantic Release
        run: npx semantic-release
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Semantic Release (Dry run)
        run: npx semantic-release --dry-run
        if: ${{ startsWith(github.ref, 'refs/heads/ci') }}
